name: .install

on:
  workflow_call:
    outputs:
      node-modules-cache-key:
        description: a max(stable) cache key to the node modules of this commit's dependencies
        value: ${{ jobs.pnpm.outputs.node-modules-cache-key }}

jobs:
  pnpm:
    runs-on: ubuntu-24.04
    outputs:
      node-modules-cache-key: ${{ steps.cache.outputs.cache-primary-key }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: node-modules deps hash
        id: deps-hash
        run: |
          PACKAGE_DEPS_HASH=$(md5sum pnpm-lock.yaml | awk '{print $1}');
          echo "PACKAGE_DEPS_HASH=$PACKAGE_DEPS_HASH"
          echo "package-deps-hash=$PACKAGE_DEPS_HASH" >> "$GITHUB_OUTPUT"

      - name: node-modules cache check
        uses: actions/cache/restore@v4
        id: cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-pnpm-${{ steps.deps-hash.outputs.package-deps-hash }}
          lookup-only: true

      - name: node-modules cache miss setup node
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: node-modules cache miss setup pnpm
        if: steps.cache.outputs.cache-hit != 'true'
        uses: pnpm/action-setup@v4

      - name: node-modules cache miss install
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: node-modules cache set
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ./node_modules
          key: ${{ steps.cache.outputs.cache-primary-key }}
